package com.vinaynalavade.expensetracker.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Embedded
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import androidx.room.Relation
import com.vinaynalavade.expensetracker.core.model.Amount
import com.vinaynalavade.expensetracker.domain.model.Category
import com.vinaynalavade.expensetracker.domain.model.RecurrenceFrequency
import com.vinaynalavade.expensetracker.domain.model.RecurringTransaction
import com.vinaynalavade.expensetracker.domain.model.TransactionType

@Entity(
    tableName = "recurring_transactions",
    foreignKeys = [
        ForeignKey(
            entity = CategoryEntity::class,
            parentColumns = ["id"],
            childColumns = ["category_id"],
            onDelete = ForeignKey.RESTRICT
        )
    ],
    indices = [
        Index(value = ["category_id"])
    ]
)
data class RecurringTransactionEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,

    @ColumnInfo(name = "title")
    val title: String,

    @ColumnInfo(name = "amount_subunits")
    val amountSubunits: Long,

    @ColumnInfo(name = "type")
    val type: String,

    @ColumnInfo(name = "category_id")
    val categoryId: Long,

    @ColumnInfo(name = "note")
    val note: String? = null,

    @ColumnInfo(name = "frequency")
    val frequency: String,

    @ColumnInfo(name = "day_of_month")
    val dayOfMonth: Int = 1,

    @ColumnInfo(name = "day_of_week")
    val dayOfWeek: Int = 1,

    @ColumnInfo(name = "start_date")
    val startDate: Long,

    @ColumnInfo(name = "end_date")
    val endDate: Long? = null,

    @ColumnInfo(name = "is_enabled")
    val isEnabled: Boolean = true,

    @ColumnInfo(name = "is_auto_generated")
    val isAutoGenerated: Boolean = true,

    @ColumnInfo(name = "reminder_days_before")
    val reminderDaysBefore: Int? = null,

    @ColumnInfo(name = "last_generated_date")
    val lastGeneratedDate: Long? = null,

    @ColumnInfo(name = "created_at")
    val createdAt: Long = System.currentTimeMillis(),

    @ColumnInfo(name = "updated_at")
    val updatedAt: Long = System.currentTimeMillis()
) {
    companion object {
        fun fromDomainModel(model: RecurringTransaction): RecurringTransactionEntity {
            return RecurringTransactionEntity(
                id = model.id,
                title = model.title,
                amountSubunits = model.amount.subunits,
                type = model.type.name,
                categoryId = model.category.id,
                note = model.note,
                frequency = model.frequency.name,
                dayOfMonth = model.dayOfMonth,
                dayOfWeek = model.dayOfWeek,
                startDate = model.startDate,
                endDate = model.endDate,
                isEnabled = model.isEnabled,
                isAutoGenerated = model.isAutoGenerated,
                reminderDaysBefore = model.reminderDaysBefore,
                lastGeneratedDate = model.lastGeneratedDate,
                createdAt = model.createdAt,
                updatedAt = model.updatedAt
            )
        }
    }
}

/**
 * Relation model for fetching recurring transaction with its associated category entity.
 */
data class RecurringWithCategory(
    @Embedded
    val recurring: RecurringTransactionEntity,

    @Relation(
        parentColumn = "category_id",
        entityColumn = "id"
    )
    val category: CategoryEntity?
) {
    fun toDomainModel(): RecurringTransaction {
        return RecurringTransaction(
            id = recurring.id,
            title = recurring.title,
            amount = Amount.fromSubunits(recurring.amountSubunits),
            type = TransactionType.fromString(recurring.type),
            category = category?.toDomainModel() ?: Category.UNCATEGORIZED,
            note = recurring.note,
            frequency = RecurrenceFrequency.fromString(recurring.frequency),
            dayOfMonth = recurring.dayOfMonth,
            dayOfWeek = recurring.dayOfWeek,
            startDate = recurring.startDate,
            endDate = recurring.endDate,
            isEnabled = recurring.isEnabled,
            isAutoGenerated = recurring.isAutoGenerated,
            reminderDaysBefore = recurring.reminderDaysBefore,
            lastGeneratedDate = recurring.lastGeneratedDate,
            createdAt = recurring.createdAt,
            updatedAt = recurring.updatedAt
        )
    }
}
