package com.vinaynalavade.expensetracker.data.repository

import androidx.room.withTransaction
import com.vinaynalavade.expensetracker.core.backup.BackupCategory
import com.vinaynalavade.expensetracker.core.backup.BackupData
import com.vinaynalavade.expensetracker.core.backup.BackupPreferences
import com.vinaynalavade.expensetracker.core.backup.BackupRecurringTransaction
import com.vinaynalavade.expensetracker.core.backup.BackupTransaction
import com.vinaynalavade.expensetracker.core.backup.BackupValidationResult
import com.vinaynalavade.expensetracker.core.backup.CsvTransactionHelper
import com.vinaynalavade.expensetracker.core.backup.ImportValidationResult
import com.vinaynalavade.expensetracker.core.backup.JsonBackupParser
import com.vinaynalavade.expensetracker.core.model.Amount
import com.vinaynalavade.expensetracker.core.model.Currency
import com.vinaynalavade.expensetracker.core.result.AppError
import com.vinaynalavade.expensetracker.core.result.AppResult
import com.vinaynalavade.expensetracker.data.local.database.ExpenseTrackerDatabase
import com.vinaynalavade.expensetracker.data.local.entity.CategoryEntity
import com.vinaynalavade.expensetracker.data.local.entity.RecurringTransactionEntity
import com.vinaynalavade.expensetracker.data.local.entity.TransactionEntity
import com.vinaynalavade.expensetracker.domain.model.Category
import com.vinaynalavade.expensetracker.domain.model.PaymentMethod
import com.vinaynalavade.expensetracker.domain.model.RecurrenceFrequency
import com.vinaynalavade.expensetracker.domain.model.ThemeMode
import com.vinaynalavade.expensetracker.domain.model.Transaction
import com.vinaynalavade.expensetracker.domain.model.TransactionType
import com.vinaynalavade.expensetracker.domain.repository.BackupRepository
import com.vinaynalavade.expensetracker.domain.repository.CategoryRepository
import com.vinaynalavade.expensetracker.domain.repository.RecurringTransactionRepository
import com.vinaynalavade.expensetracker.domain.repository.TransactionRepository
import com.vinaynalavade.expensetracker.domain.repository.UserPreferencesRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.firstOrNull

class BackupRepositoryImpl(
    private val database: ExpenseTrackerDatabase,
    private val transactionRepository: TransactionRepository,
    private val categoryRepository: CategoryRepository,
    private val recurringTransactionRepository: RecurringTransactionRepository,
    private val userPreferencesRepository: UserPreferencesRepository
) : BackupRepository {

    override fun getLastBackupTimestamp(): Flow<Long?> {
        return userPreferencesRepository.getLastBackupTimestamp()
    }

    override suspend fun createFullBackup(): AppResult<BackupData> {
        return try {
            val categories = categoryRepository.getCategories().firstOrNull() ?: emptyList()
            val transactions = transactionRepository.getTransactions().firstOrNull() ?: emptyList()
            val recurringList = recurringTransactionRepository.getRecurringTransactions().firstOrNull() ?: emptyList()
            val prefs = userPreferencesRepository.getUserPreferences().firstOrNull()

            val backupCategories = categories.map { cat ->
                BackupCategory(
                    id = cat.id,
                    name = cat.name,
                    iconName = cat.iconName,
                    colorHex = cat.colorHex,
                    type = cat.type.name,
                    isDefault = cat.isDefault
                )
            }

            val backupTransactions = transactions.map { tx ->
                BackupTransaction(
                    id = tx.id,
                    amountSubunits = tx.amount.subunits,
                    type = tx.type.name,
                    categoryId = tx.category.id,
                    paymentMethod = tx.paymentMethod.name,
                    note = tx.note,
                    timestamp = tx.timestamp
                )
            }

            val backupRecurring = recurringList.map { rec ->
                BackupRecurringTransaction(
                    id = rec.id,
                    title = rec.title,
                    amountSubunits = rec.amount.subunits,
                    type = rec.type.name,
                    categoryId = rec.category.id,
                    paymentMethod = rec.paymentMethod.name,
                    note = rec.note,
                    frequency = rec.frequency.name,
                    dayOfMonth = rec.dayOfMonth,
                    dayOfWeek = rec.dayOfWeek,
                    startDate = rec.startDate,
                    endDate = rec.endDate,
                    isEnabled = rec.isEnabled,
                    isAutoGenerated = rec.isAutoGenerated,
                    reminderDaysBefore = rec.reminderDaysBefore,
                    lastGeneratedDate = rec.lastGeneratedDate,
                    createdAt = rec.createdAt,
                    updatedAt = rec.updatedAt
                )
            }

            val backupPreferences = BackupPreferences(
                openingBalanceSubunits = prefs?.openingBalanceSubunits ?: 0L,
                currencyCode = prefs?.currency?.code ?: "INR",
                themeMode = prefs?.themeMode?.name ?: "SYSTEM",
                dailyReminderEnabled = prefs?.dailyReminderEnabled ?: false,
                dailyReminderHour = prefs?.dailyReminderHour ?: 21,
                dailyReminderMinute = prefs?.dailyReminderMinute ?: 0,
                emiRemindersEnabled = prefs?.emiRemindersEnabled ?: true
            )

            val now = System.currentTimeMillis()
            val backupData = BackupData(
                backupVersion = BackupData.CURRENT_VERSION,
                appVersion = "1.0.1",
                createdAt = now,
                categories = backupCategories,
                transactions = backupTransactions,
                recurringTransactions = backupRecurring,
                preferences = backupPreferences
            )

            userPreferencesRepository.setLastBackupTimestamp(now)
            AppResult.Success(backupData)
        } catch (e: Exception) {
            AppResult.Error(AppError.DatabaseError(e.message ?: "Failed to create backup.", e))
        }
    }

    override suspend fun validateBackupJson(jsonString: String): BackupValidationResult {
        return try {
            val backup = JsonBackupParser.fromJson(jsonString)

            if (backup.backupVersion > BackupData.CURRENT_VERSION) {
                return BackupValidationResult.Invalid("Backup version ${backup.backupVersion} is newer than supported version (${BackupData.CURRENT_VERSION}). Please update KharchaFlow.")
            }
            if (backup.backupVersion <= 0) {
                return BackupValidationResult.Invalid("Invalid backup version ${backup.backupVersion}.")
            }

            if (backup.categories.isEmpty()) {
                return BackupValidationResult.Invalid("Corrupted backup: No categories found in file.")
            }

            val categoryIds = backup.categories.map { it.id }.toSet()

            // Validate that all transactions have valid categories and amounts
            for (tx in backup.transactions) {
                if (tx.amountSubunits <= 0L) {
                    return BackupValidationResult.Invalid("Invalid transaction amount in backup (ID: ${tx.id}).")
                }
                if (tx.categoryId !in categoryIds) {
                    return BackupValidationResult.Invalid("Relationship integrity error: Transaction ${tx.id} references missing category ${tx.categoryId}.")
                }
                if (tx.type != "EXPENSE" && tx.type != "INCOME") {
                    return BackupValidationResult.Invalid("Invalid transaction type '${tx.type}' for transaction ${tx.id}.")
                }
            }

            // Validate recurring transactions
            for (rec in backup.recurringTransactions) {
                if (rec.amountSubunits <= 0L) {
                    return BackupValidationResult.Invalid("Invalid recurring amount in backup (ID: ${rec.id}).")
                }
                if (rec.categoryId !in categoryIds) {
                    return BackupValidationResult.Invalid("Relationship integrity error: Recurring transaction ${rec.id} references missing category ${rec.categoryId}.")
                }
            }

            BackupValidationResult.Valid(
                backupData = backup,
                transactionCount = backup.transactions.size,
                categoryCount = backup.categories.size,
                recurringCount = backup.recurringTransactions.size,
                createdAt = backup.createdAt,
                appVersion = backup.appVersion
            )
        } catch (e: Exception) {
            BackupValidationResult.Invalid(e.message ?: "Malformed or unreadable backup file.")
        }
    }

    override suspend fun restoreFullBackup(backupData: BackupData): AppResult<Unit> {
        return try {
            val categoryEntities = backupData.categories.map { cat ->
                CategoryEntity(
                    id = cat.id,
                    name = cat.name,
                    iconName = cat.iconName,
                    colorHex = cat.colorHex,
                    type = cat.type,
                    isDefault = cat.isDefault
                )
            }

            val transactionEntities = backupData.transactions.map { tx ->
                TransactionEntity(
                    id = tx.id,
                    amountSubunits = tx.amountSubunits,
                    type = tx.type,
                    categoryId = tx.categoryId,
                    paymentMethod = tx.paymentMethod,
                    note = tx.note,
                    timestamp = tx.timestamp
                )
            }

            val recurringEntities = backupData.recurringTransactions.map { rec ->
                RecurringTransactionEntity(
                    id = rec.id,
                    title = rec.title,
                    amountSubunits = rec.amountSubunits,
                    type = rec.type,
                    categoryId = rec.categoryId,
                    paymentMethod = rec.paymentMethod,
                    note = rec.note,
                    frequency = rec.frequency,
                    dayOfMonth = rec.dayOfMonth,
                    dayOfWeek = rec.dayOfWeek,
                    startDate = rec.startDate,
                    endDate = rec.endDate,
                    isEnabled = rec.isEnabled,
                    isAutoGenerated = rec.isAutoGenerated,
                    reminderDaysBefore = rec.reminderDaysBefore,
                    lastGeneratedDate = rec.lastGeneratedDate,
                    createdAt = rec.createdAt,
                    updatedAt = rec.updatedAt
                )
            }

            // Execute in an atomic database transaction
            database.withTransaction {
                database.recurringTransactionDao().deleteAllRecurringTransactions()
                database.transactionDao().deleteAllTransactions()
                database.categoryDao().deleteAllCategories()

                database.categoryDao().insertOrUpdateCategories(categoryEntities)
                database.transactionDao().insertTransactions(transactionEntities)
                database.recurringTransactionDao().insertRecurringTransactions(recurringEntities)
            }

            // Restore user preferences
            userPreferencesRepository.setOpeningBalance(backupData.preferences.openingBalanceSubunits)
            userPreferencesRepository.setCurrencyCode(backupData.preferences.currencyCode)
            userPreferencesRepository.setThemeMode(ThemeMode.fromString(backupData.preferences.themeMode))
            userPreferencesRepository.setDailyReminder(
                backupData.preferences.dailyReminderEnabled,
                backupData.preferences.dailyReminderHour,
                backupData.preferences.dailyReminderMinute
            )
            userPreferencesRepository.setEmiReminders(backupData.preferences.emiRemindersEnabled)
            userPreferencesRepository.setLastBackupTimestamp(System.currentTimeMillis())

            AppResult.Success(Unit)
        } catch (e: Exception) {
            AppResult.Error(AppError.DatabaseError(e.message ?: "Failed to restore backup.", e))
        }
    }

    override suspend fun getFilteredTransactions(
        startDate: Long?,
        endDate: Long?,
        type: TransactionType?,
        categoryId: Long?
    ): AppResult<List<Transaction>> {
        return try {
            val allTransactions = if (startDate != null && endDate != null) {
                transactionRepository.getTransactionsBetween(startDate, endDate).firstOrNull() ?: emptyList()
            } else {
                transactionRepository.getTransactions().firstOrNull() ?: emptyList()
            }

            val filtered = allTransactions.filter { tx ->
                val matchesType = type == null || tx.type == type
                val matchesCategory = categoryId == null || tx.category.id == categoryId
                matchesType && matchesCategory
            }

            AppResult.Success(filtered)
        } catch (e: Exception) {
            AppResult.Error(AppError.DatabaseError(e.message ?: "Failed to query transactions.", e))
        }
    }

    override suspend fun validateAndPrepareImportCsv(
        csvContent: String,
        defaultCurrency: Currency
    ): ImportValidationResult {
        val existingCategories = categoryRepository.getCategories().firstOrNull() ?: emptyList()
        val parsedRows = CsvTransactionHelper.parseCsv(csvContent, defaultCurrency)
        val validTransactions = mutableListOf<Transaction>()
        val issues = mutableListOf<String>()

        for (row in parsedRows) {
            if (!row.isValid) {
                issues.add(row.errorMessage ?: "Row ${row.rowIndex}: Invalid data")
                continue
            }

            val matchedCategory = existingCategories.find {
                it.name.trim().equals(row.categoryName?.trim(), ignoreCase = true) &&
                        it.type == row.type
            } ?: existingCategories.find {
                it.type == row.type && it.isDefault
            } ?: Category.UNCATEGORIZED

            validTransactions.add(
                Transaction(
                    id = 0L,
                    amount = row.amount ?: Amount.ZERO,
                    type = row.type ?: TransactionType.EXPENSE,
                    category = matchedCategory,
                    paymentMethod = row.paymentMethod,
                    note = row.note,
                    timestamp = row.dateEpoch ?: System.currentTimeMillis()
                )
            )
        }

        return ImportValidationResult(
            totalRows = parsedRows.size,
            validTransactions = validTransactions,
            issues = issues
        )
    }

    override suspend fun validateAndPrepareImportJson(jsonContent: String): ImportValidationResult {
        return try {
            val parsedTxList = JsonBackupParser.parseTransactionsJson(jsonContent)
            val existingCategories = categoryRepository.getCategories().firstOrNull() ?: emptyList()
            val validTransactions = mutableListOf<Transaction>()
            val issues = mutableListOf<String>()

            for ((index, item) in parsedTxList.withIndex()) {
                val type = try {
                    TransactionType.fromString(item.type)
                } catch (_: Exception) {
                    issues.add("Item ${index + 1}: Invalid transaction type '${item.type}'")
                    continue
                }

                val matchedCategory = existingCategories.find { it.id == item.categoryId }
                    ?: existingCategories.find { it.type == type && it.isDefault }
                    ?: Category.UNCATEGORIZED

                val paymentMethod = try {
                    PaymentMethod.fromString(item.paymentMethod)
                } catch (_: Exception) {
                    PaymentMethod.CASH
                }

                validTransactions.add(
                    Transaction(
                        id = 0L,
                        amount = Amount(item.amountSubunits),
                        type = type,
                        category = matchedCategory,
                        paymentMethod = paymentMethod,
                        note = item.note,
                        timestamp = item.timestamp
                    )
                )
            }

            ImportValidationResult(
                totalRows = parsedTxList.size,
                validTransactions = validTransactions,
                issues = issues
            )
        } catch (e: Exception) {
            ImportValidationResult(
                totalRows = 0,
                validTransactions = emptyList(),
                issues = listOf(e.message ?: "Failed to parse JSON file.")
            )
        }
    }

    override suspend fun importTransactions(transactions: List<Transaction>): AppResult<Int> {
        return try {
            var count = 0
            for (tx in transactions) {
                val result = transactionRepository.insertTransaction(tx)
                if (result is AppResult.Success) {
                    count++
                }
            }
            AppResult.Success(count)
        } catch (e: Exception) {
            AppResult.Error(AppError.DatabaseError(e.message ?: "Failed to import transactions.", e))
        }
    }
}
