package com.vinaynalavade.expensetracker.data.repository

import com.vinaynalavade.expensetracker.core.result.AppError
import com.vinaynalavade.expensetracker.core.result.AppResult
import com.vinaynalavade.expensetracker.core.utils.DateTimeUtils
import com.vinaynalavade.expensetracker.data.local.dao.RecurringTransactionDao
import com.vinaynalavade.expensetracker.data.local.dao.TransactionDao
import com.vinaynalavade.expensetracker.data.local.entity.RecurringTransactionEntity
import com.vinaynalavade.expensetracker.data.local.entity.TransactionEntity
import com.vinaynalavade.expensetracker.domain.model.RecurrenceFrequency
import com.vinaynalavade.expensetracker.domain.model.RecurringTransaction
import com.vinaynalavade.expensetracker.domain.repository.RecurringTransactionRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import java.time.DayOfWeek
import java.time.Instant
import java.time.LocalDate
import java.time.YearMonth
import java.time.ZoneId
import java.time.temporal.TemporalAdjusters

class RecurringTransactionRepositoryImpl(
    private val recurringTransactionDao: RecurringTransactionDao,
    private val transactionDao: TransactionDao
) : RecurringTransactionRepository {

    override fun getRecurringTransactions(): Flow<List<RecurringTransaction>> {
        return recurringTransactionDao.getAllRecurringWithCategory().map { list ->
            list.map { it.toDomainModel() }
        }
    }

    override fun getRecurringTransactionById(id: Long): Flow<RecurringTransaction?> {
        return recurringTransactionDao.getRecurringWithCategoryById(id).map { item ->
            item?.toDomainModel()
        }
    }

    override suspend fun insertRecurringTransaction(recurringTransaction: RecurringTransaction): AppResult<Long> {
        return try {
            val entity = RecurringTransactionEntity.fromDomainModel(recurringTransaction)
            val id = recurringTransactionDao.insertRecurringTransaction(entity)
            AppResult.Success(id)
        } catch (e: Exception) {
            AppResult.Error(AppError.DatabaseError(e.message ?: "Failed to insert recurring transaction.", e))
        }
    }

    override suspend fun updateRecurringTransaction(recurringTransaction: RecurringTransaction): AppResult<Unit> {
        return try {
            val entity = RecurringTransactionEntity.fromDomainModel(recurringTransaction)
            recurringTransactionDao.updateRecurringTransaction(entity)
            AppResult.Success(Unit)
        } catch (e: Exception) {
            AppResult.Error(AppError.DatabaseError(e.message ?: "Failed to update recurring transaction.", e))
        }
    }

    override suspend fun deleteRecurringTransaction(id: Long): AppResult<Unit> {
        return try {
            recurringTransactionDao.deleteRecurringTransactionById(id)
            AppResult.Success(Unit)
        } catch (e: Exception) {
            AppResult.Error(AppError.DatabaseError(e.message ?: "Failed to delete recurring transaction.", e))
        }
    }

    override suspend fun processDueOccurrences(): AppResult<Int> {
        return try {
            val activeItems = recurringTransactionDao.getActiveRecurringTransactions()
            val today = LocalDate.now()
            val nowEpoch = System.currentTimeMillis()
            var processedCount = 0

            for (item in activeItems) {
                val recurring = item.recurring
                if (!recurring.isAutoGenerated || !recurring.isEnabled) continue

                val isDue = checkIfDue(recurring, today)
                if (isDue) {
                    // Insert a new transaction
                    val txEntity = TransactionEntity(
                        amountSubunits = recurring.amountSubunits,
                        type = recurring.type,
                        categoryId = recurring.categoryId,
                        paymentMethod = recurring.paymentMethod,
                        note = recurring.note ?: recurring.title,
                        timestamp = nowEpoch,
                        createdAt = nowEpoch,
                        updatedAt = nowEpoch
                    )
                    transactionDao.insertTransaction(txEntity)

                    // Update last generated date
                    recurringTransactionDao.updateRecurringTransaction(
                        recurring.copy(
                            lastGeneratedDate = nowEpoch,
                            updatedAt = nowEpoch
                        )
                    )
                    processedCount++
                }
            }
            AppResult.Success(processedCount)
        } catch (e: Exception) {
            AppResult.Error(AppError.DatabaseError(e.message ?: "Failed to process due recurring transactions.", e))
        }
    }

    internal fun checkIfDue(recurring: RecurringTransactionEntity, today: LocalDate): Boolean {
        val freq = RecurrenceFrequency.fromStringOrNull(recurring.frequency) ?: return false

        // Check end date boundary
        if (recurring.endDate != null) {
            val endDate = Instant.ofEpochMilli(recurring.endDate).atZone(ZoneId.systemDefault()).toLocalDate()
            if (today.isAfter(endDate)) return false
        }

        val startEpoch = if (recurring.startDate > 0L) recurring.startDate else recurring.createdAt
        val startDate = Instant.ofEpochMilli(startEpoch).atZone(ZoneId.systemDefault()).toLocalDate()
        if (today.isBefore(startDate)) return false

        val lastGenerated = recurring.lastGeneratedDate?.let {
            Instant.ofEpochMilli(it).atZone(ZoneId.systemDefault()).toLocalDate()
        }

        return when (freq) {
            RecurrenceFrequency.DAILY -> {
                if (lastGenerated == null) {
                    !today.isBefore(startDate)
                } else {
                    today.isAfter(lastGenerated)
                }
            }
            RecurrenceFrequency.WEEKLY -> {
                val targetDayOfWeek = recurring.dayOfWeek.coerceIn(1, 7)
                val startOfWeek = today.with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY))
                val generatedThisWeek = lastGenerated != null && !lastGenerated.isBefore(startOfWeek)

                if (generatedThisWeek) {
                    false
                } else if (lastGenerated == null) {
                    var firstOccurrence = startDate
                    while (firstOccurrence.dayOfWeek.value != targetDayOfWeek) {
                        firstOccurrence = firstOccurrence.plusDays(1)
                    }
                    !today.isBefore(firstOccurrence) && today.dayOfWeek.value >= targetDayOfWeek
                } else {
                    today.dayOfWeek.value >= targetDayOfWeek
                }
            }
            RecurrenceFrequency.MONTHLY -> {
                val currentMonth = YearMonth.from(today)
                val scheduledDayThisMonth = DateTimeUtils.getScheduledDayOfMonth(recurring.dayOfMonth, currentMonth)

                if (lastGenerated != null) {
                    val lastGeneratedMonth = YearMonth.from(lastGenerated)
                    currentMonth.isAfter(lastGeneratedMonth) && today.dayOfMonth >= scheduledDayThisMonth
                } else {
                    val startMonth = YearMonth.from(startDate)
                    val scheduledDayInStartMonth = DateTimeUtils.getScheduledDayOfMonth(recurring.dayOfMonth, startMonth)
                    val firstScheduledDate = if (startDate.dayOfMonth > scheduledDayInStartMonth) {
                        val nextMonth = startMonth.plusMonths(1)
                        val scheduledDayInNextMonth = DateTimeUtils.getScheduledDayOfMonth(recurring.dayOfMonth, nextMonth)
                        nextMonth.atDay(scheduledDayInNextMonth)
                    } else {
                        startMonth.atDay(scheduledDayInStartMonth)
                    }

                    !today.isBefore(firstScheduledDate)
                }
            }
            RecurrenceFrequency.YEARLY -> {
                val targetMonth = YearMonth.of(today.year, startDate.month)
                val scheduledDayThisYear = DateTimeUtils.getScheduledDayOfMonth(recurring.dayOfMonth, targetMonth)
                val scheduledDateThisYear = targetMonth.atDay(scheduledDayThisYear)

                if (lastGenerated != null) {
                    today.year > lastGenerated.year && !today.isBefore(scheduledDateThisYear)
                } else {
                    val startYearMonth = YearMonth.of(startDate.year, startDate.month)
                    val scheduledDayInStartYear = DateTimeUtils.getScheduledDayOfMonth(recurring.dayOfMonth, startYearMonth)
                    val scheduledDateInStartYear = startYearMonth.atDay(scheduledDayInStartYear)

                    val firstScheduledDate = if (startDate.isAfter(scheduledDateInStartYear)) {
                        val nextYearMonth = startYearMonth.plusYears(1)
                        val nextScheduledDay = DateTimeUtils.getScheduledDayOfMonth(recurring.dayOfMonth, nextYearMonth)
                        nextYearMonth.atDay(nextScheduledDay)
                    } else {
                        scheduledDateInStartYear
                    }

                    !today.isBefore(firstScheduledDate)
                }
            }
        }
    }
}
