package com.vinaynalavade.expensetracker.data.repository

import com.vinaynalavade.expensetracker.core.result.AppError
import com.vinaynalavade.expensetracker.core.result.AppResult
import com.vinaynalavade.expensetracker.data.local.dao.RecurringTransactionDao
import com.vinaynalavade.expensetracker.data.local.dao.TransactionDao
import com.vinaynalavade.expensetracker.data.local.entity.RecurringTransactionEntity
import com.vinaynalavade.expensetracker.data.local.entity.TransactionEntity
import com.vinaynalavade.expensetracker.domain.model.RecurrenceFrequency
import com.vinaynalavade.expensetracker.domain.model.RecurringTransaction
import com.vinaynalavade.expensetracker.domain.repository.RecurringTransactionRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import java.time.Instant
import java.time.LocalDate
import java.time.ZoneId

class RecurringTransactionRepositoryImpl(
    private val recurringTransactionDao: RecurringTransactionDao,
    private val transactionDao: TransactionDao
) : RecurringTransactionRepository {

    override fun getRecurringTransactions(): Flow<List<RecurringTransaction>> {
        return recurringTransactionDao.getAllRecurringWithCategory().map { list ->
            list.map { it.toDomainModel() }
        }
    }

    override fun getRecurringTransactionById(id: Long): Flow<RecurringTransaction?> {
        return recurringTransactionDao.getRecurringWithCategoryById(id).map { item ->
            item?.toDomainModel()
        }
    }

    override suspend fun insertRecurringTransaction(recurringTransaction: RecurringTransaction): AppResult<Long> {
        return try {
            val entity = RecurringTransactionEntity.fromDomainModel(recurringTransaction)
            val id = recurringTransactionDao.insertRecurringTransaction(entity)
            AppResult.Success(id)
        } catch (e: Exception) {
            AppResult.Error(AppError.DatabaseError(e.message ?: "Failed to insert recurring transaction.", e))
        }
    }

    override suspend fun updateRecurringTransaction(recurringTransaction: RecurringTransaction): AppResult<Unit> {
        return try {
            val entity = RecurringTransactionEntity.fromDomainModel(recurringTransaction)
            recurringTransactionDao.updateRecurringTransaction(entity)
            AppResult.Success(Unit)
        } catch (e: Exception) {
            AppResult.Error(AppError.DatabaseError(e.message ?: "Failed to update recurring transaction.", e))
        }
    }

    override suspend fun deleteRecurringTransaction(id: Long): AppResult<Unit> {
        return try {
            recurringTransactionDao.deleteRecurringTransactionById(id)
            AppResult.Success(Unit)
        } catch (e: Exception) {
            AppResult.Error(AppError.DatabaseError(e.message ?: "Failed to delete recurring transaction.", e))
        }
    }

    override suspend fun processDueOccurrences(): AppResult<Int> {
        return try {
            val activeItems = recurringTransactionDao.getActiveRecurringTransactions()
            val today = LocalDate.now()
            val nowEpoch = System.currentTimeMillis()
            var processedCount = 0

            for (item in activeItems) {
                val recurring = item.recurring
                if (!recurring.isAutoGenerated || !recurring.isEnabled) continue

                val isDue = checkIfDue(recurring, today)
                if (isDue) {
                    // Insert a new transaction
                    val txEntity = TransactionEntity(
                        amountSubunits = recurring.amountSubunits,
                        type = recurring.type,
                        categoryId = recurring.categoryId,
                        paymentMethod = recurring.paymentMethod,
                        note = recurring.note ?: recurring.title,
                        timestamp = nowEpoch,
                        createdAt = nowEpoch,
                        updatedAt = nowEpoch
                    )
                    transactionDao.insertTransaction(txEntity)

                    // Update last generated date
                    recurringTransactionDao.updateRecurringTransaction(
                        recurring.copy(
                            lastGeneratedDate = nowEpoch,
                            updatedAt = nowEpoch
                        )
                    )
                    processedCount++
                }
            }
            AppResult.Success(processedCount)
        } catch (e: Exception) {
            AppResult.Error(AppError.DatabaseError(e.message ?: "Failed to process due recurring transactions.", e))
        }
    }

    private fun checkIfDue(recurring: RecurringTransactionEntity, today: LocalDate): Boolean {
        val freq = RecurrenceFrequency.fromStringOrNull(recurring.frequency) ?: return false

        val lastGenerated = recurring.lastGeneratedDate?.let {
            Instant.ofEpochMilli(it).atZone(ZoneId.systemDefault()).toLocalDate()
        }

        return when (freq) {
            RecurrenceFrequency.DAILY -> {
                lastGenerated == null || lastGenerated.isBefore(today)
            }
            RecurrenceFrequency.WEEKLY -> {
                (lastGenerated == null || lastGenerated.isBefore(today)) && today.dayOfWeek.value == recurring.dayOfWeek
            }
            RecurrenceFrequency.MONTHLY -> {
                (lastGenerated == null || (lastGenerated.year < today.year || lastGenerated.monthValue < today.monthValue)) &&
                        today.dayOfMonth >= recurring.dayOfMonth
            }
            RecurrenceFrequency.YEARLY -> {
                (lastGenerated == null || lastGenerated.year < today.year) &&
                        today.dayOfMonth >= recurring.dayOfMonth
            }
        }
    }
}
