package com.vinaynalavade.expensetracker.presentation.recurring

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Switch
import androidx.compose.material3.Tab
import androidx.compose.material3.TabRow
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import com.vinaynalavade.expensetracker.core.model.Amount
import com.vinaynalavade.expensetracker.core.model.Currency
import com.vinaynalavade.expensetracker.domain.model.Category
import com.vinaynalavade.expensetracker.domain.model.RecurrenceFrequency
import com.vinaynalavade.expensetracker.domain.model.RecurringTransaction
import com.vinaynalavade.expensetracker.domain.model.TransactionType
import com.vinaynalavade.expensetracker.presentation.entry.components.CategorySelector
import com.vinaynalavade.expensetracker.presentation.theme.ButtonShape
import com.vinaynalavade.expensetracker.presentation.theme.CardShape
import com.vinaynalavade.expensetracker.presentation.theme.LocalCurrency
import com.vinaynalavade.expensetracker.presentation.theme.spacing

@Composable
fun AddEditRecurringDialog(
    itemToEdit: RecurringTransaction?,
    availableCategories: List<Category>,
    onDismiss: () -> Unit,
    onSave: (RecurringTransaction) -> Unit,
    currency: Currency = LocalCurrency.current
) {
    var title by remember { mutableStateOf(itemToEdit?.title ?: "") }
    var amountText by remember { mutableStateOf(itemToEdit?.amount?.toInputString(currency) ?: "") }
    var selectedType by remember { mutableStateOf(itemToEdit?.type ?: TransactionType.EXPENSE) }
    var selectedCategory by remember {
        mutableStateOf(itemToEdit?.category ?: availableCategories.firstOrNull { it.type == selectedType })
    }
    var selectedFrequency by remember { mutableStateOf(itemToEdit?.frequency ?: RecurrenceFrequency.MONTHLY) }
    var dayOfMonth by remember { mutableIntStateOf(itemToEdit?.dayOfMonth ?: 1) }
    var isAutoGenerated by remember { mutableStateOf(itemToEdit?.isAutoGenerated ?: true) }
    var reminderDaysBefore by remember { mutableStateOf(itemToEdit?.reminderDaysBefore?.toString() ?: "1") }

    val filteredCategories = availableCategories.filter { it.type == selectedType }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = {
            Text(
                text = if (itemToEdit == null) "Schedule Recurring / EMI" else "Edit Recurring Transaction",
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.Bold
            )
        },
        text = {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .verticalScroll(rememberScrollState())
            ) {
                // Type Tabs
                TabRow(selectedTabIndex = selectedType.ordinal) {
                    TransactionType.entries.forEach { type ->
                        Tab(
                            selected = selectedType == type,
                            onClick = {
                                selectedType = type
                                selectedCategory = availableCategories.firstOrNull { it.type == type }
                            },
                            text = { Text(type.displayName) }
                        )
                    }
                }

                Spacer(modifier = Modifier.height(MaterialTheme.spacing.md))

                // Title Input
                OutlinedTextField(
                    value = title,
                    onValueChange = { title = it },
                    label = { Text("Title (e.g. Monthly Salary, Home Rent, Car EMI)") },
                    singleLine = true,
                    shape = ButtonShape,
                    modifier = Modifier.fillMaxWidth()
                )

                Spacer(modifier = Modifier.height(MaterialTheme.spacing.sm))

                // Amount Input
                OutlinedTextField(
                    value = amountText,
                    onValueChange = { input ->
                        if (input.all { it.isDigit() || it == '.' }) amountText = input
                    },
                    label = { Text("Amount (${currency.symbol})") },
                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Decimal),
                    singleLine = true,
                    shape = ButtonShape,
                    modifier = Modifier.fillMaxWidth()
                )

                Spacer(modifier = Modifier.height(MaterialTheme.spacing.md))

                // Category Selector
                CategorySelector(
                    categories = filteredCategories,
                    selectedCategory = selectedCategory,
                    onCategorySelect = { selectedCategory = it }
                )

                Spacer(modifier = Modifier.height(MaterialTheme.spacing.md))

                // Day of Month
                OutlinedTextField(
                    value = dayOfMonth.toString(),
                    onValueChange = {
                        val num = it.toIntOrNull()
                        if (num != null && num in 1..31) dayOfMonth = num
                    },
                    label = { Text("Day of Month (1 - 31)") },
                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
                    singleLine = true,
                    shape = ButtonShape,
                    modifier = Modifier.fillMaxWidth()
                )

                Spacer(modifier = Modifier.height(MaterialTheme.spacing.md))

                // Auto-generate Switch
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Column(modifier = Modifier.weight(1f)) {
                        Text(text = "Auto-create Transaction", style = MaterialTheme.typography.bodyMedium, fontWeight = FontWeight.SemiBold)
                        Text(text = "Automatically records to ledger on due date", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                    }
                    Switch(checked = isAutoGenerated, onCheckedChange = { isAutoGenerated = it })
                }
            }
        },
        confirmButton = {
            TextButton(
                onClick = {
                    val parsedAmount = Amount.fromStringOrNull(amountText, currency)
                    val cat = selectedCategory
                    if (title.isNotBlank() && parsedAmount != null && cat != null) {
                        val newItem = RecurringTransaction(
                            id = itemToEdit?.id ?: 0L,
                            title = title.trim(),
                            amount = parsedAmount,
                            type = selectedType,
                            category = cat,
                            frequency = selectedFrequency,
                            dayOfMonth = dayOfMonth,
                            isEnabled = true,
                            isAutoGenerated = isAutoGenerated,
                            reminderDaysBefore = reminderDaysBefore.toIntOrNull(),
                            lastGeneratedDate = itemToEdit?.lastGeneratedDate
                        )
                        onSave(newItem)
                    }
                },
                enabled = title.isNotBlank() && amountText.isNotBlank() && selectedCategory != null
            ) {
                Text(text = "Save", fontWeight = FontWeight.Bold)
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) {
                Text(text = "Cancel")
            }
        },
        shape = CardShape,
        containerColor = MaterialTheme.colorScheme.surface
    )
}
