package com.vinaynalavade.expensetracker.core.backup

/**
 * Versioned, full-application backup container.
 */
data class BackupData(
    val backupVersion: Int = CURRENT_VERSION,
    val appVersion: String = "1.0.1",
    val createdAt: Long = System.currentTimeMillis(),
    val categories: List<BackupCategory>,
    val transactions: List<BackupTransaction>,
    val recurringTransactions: List<BackupRecurringTransaction> = emptyList(),
    val preferences: BackupPreferences
) {
    companion object {
        const val CURRENT_VERSION = 1
    }
}

data class BackupCategory(
    val id: Long,
    val name: String,
    val iconName: String,
    val colorHex: String,
    val type: String, // "EXPENSE" or "INCOME"
    val isDefault: Boolean = false
)

data class BackupTransaction(
    val id: Long,
    val amountSubunits: Long,
    val type: String, // "EXPENSE" or "INCOME"
    val categoryId: Long,
    val paymentMethod: String = "CASH", // "CASH", "BANK_ACCOUNT", "UPI"
    val note: String? = null,
    val timestamp: Long
)

data class BackupRecurringTransaction(
    val id: Long,
    val title: String,
    val amountSubunits: Long,
    val type: String,
    val categoryId: Long,
    val paymentMethod: String = "CASH",
    val note: String? = null,
    val frequency: String,
    val dayOfMonth: Int,
    val dayOfWeek: Int,
    val startDate: Long,
    val endDate: Long? = null,
    val isEnabled: Boolean = true,
    val isAutoGenerated: Boolean = true,
    val reminderDaysBefore: Int? = 1,
    val lastGeneratedDate: Long? = null,
    val createdAt: Long,
    val updatedAt: Long
)

data class BackupPreferences(
    val openingBalanceSubunits: Long = 0L,
    val currencyCode: String = "INR",
    val themeMode: String = "SYSTEM",
    val dailyReminderEnabled: Boolean = false,
    val dailyReminderHour: Int = 21,
    val dailyReminderMinute: Int = 0,
    val emiRemindersEnabled: Boolean = true,
    val notificationsMasterEnabled: Boolean = false,
    val budgetAlertsEnabled: Boolean = false,
    val monthlyBudgetLimitSubunits: Long = 0L,
    val recurringRemindersEnabled: Boolean = false,
    val recurringReminderAdvanceDays: Int = 1,
    val savingsGoalNotificationsEnabled: Boolean = false
)
