package com.vinaynalavade.expensetracker

import com.vinaynalavade.expensetracker.core.backup.BackupCategory
import com.vinaynalavade.expensetracker.core.backup.BackupData
import com.vinaynalavade.expensetracker.core.backup.BackupPreferences
import com.vinaynalavade.expensetracker.core.backup.BackupRecurringTransaction
import com.vinaynalavade.expensetracker.core.backup.BackupTransaction
import com.vinaynalavade.expensetracker.core.backup.JsonBackupParser
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Test

class BackupSerializationTest {

    @Test
    fun testFullBackupJsonSerializationAndDeserializationRoundtrip() {
        val original = BackupData(
            backupVersion = 1,
            appVersion = "1.0.1",
            createdAt = 1787410000000L,
            categories = listOf(
                BackupCategory(1L, "Food & Dining", "restaurant", "#EF4444", "EXPENSE", true),
                BackupCategory(2L, "Salary", "payments", "#10B981", "INCOME", true)
            ),
            transactions = listOf(
                BackupTransaction(101L, 25000L, "EXPENSE", 1L, "UPI", "Dinner with \"friends\", and drinks\nNext line", 1787400000000L),
                BackupTransaction(102L, 5000000L, "INCOME", 2L, "BANK_ACCOUNT", null, 1787300000000L)
            ),
            recurringTransactions = listOf(
                BackupRecurringTransaction(
                    id = 1L,
                    title = "House Rent",
                    amountSubunits = 2500000L,
                    type = "EXPENSE",
                    categoryId = 1L,
                    paymentMethod = "BANK_ACCOUNT",
                    note = "Monthly Rent",
                    frequency = "MONTHLY",
                    dayOfMonth = 1,
                    dayOfWeek = 1,
                    startDate = 1787000000000L,
                    endDate = null,
                    isEnabled = true,
                    isAutoGenerated = true,
                    reminderDaysBefore = 2,
                    lastGeneratedDate = 1787100000000L,
                    createdAt = 1787000000000L,
                    updatedAt = 1787000000000L
                )
            ),
            preferences = BackupPreferences(
                openingBalanceSubunits = 10000000L,
                currencyCode = "INR",
                themeMode = "DARK",
                dailyReminderEnabled = true,
                dailyReminderHour = 21,
                dailyReminderMinute = 30,
                emiRemindersEnabled = true
            )
        )

        // Serialize
        val json = JsonBackupParser.toJson(original)
        assertTrue(json.contains("\"backupVersion\": 1"))
        assertTrue(json.contains("\"appVersion\": \"1.0.1\""))
        assertTrue(json.contains("\"Food & Dining\""))
        assertTrue(json.contains("Dinner with \\\"friends\\\", and drinks\\nNext line"))

        // Deserialize
        val deserialized = JsonBackupParser.fromJson(json)

        assertEquals(original.backupVersion, deserialized.backupVersion)
        assertEquals(original.appVersion, deserialized.appVersion)
        assertEquals(original.createdAt, deserialized.createdAt)
        assertEquals(2, deserialized.categories.size)
        assertEquals("Food & Dining", deserialized.categories[0].name)
        assertEquals("Salary", deserialized.categories[1].name)

        assertEquals(2, deserialized.transactions.size)
        assertEquals(101L, deserialized.transactions[0].id)
        assertEquals("UPI", deserialized.transactions[0].paymentMethod)
        assertEquals("Dinner with \"friends\", and drinks\nNext line", deserialized.transactions[0].note)
        assertEquals("BANK_ACCOUNT", deserialized.transactions[1].paymentMethod)

        assertEquals(1, deserialized.recurringTransactions.size)
        assertEquals("House Rent", deserialized.recurringTransactions[0].title)

        assertEquals(10000000L, deserialized.preferences.openingBalanceSubunits)
        assertEquals("INR", deserialized.preferences.currencyCode)
        assertEquals("DARK", deserialized.preferences.themeMode)
        assertTrue(deserialized.preferences.dailyReminderEnabled)
        assertEquals(21, deserialized.preferences.dailyReminderHour)
        assertEquals(30, deserialized.preferences.dailyReminderMinute)
    }

    @Test
    fun testTransactionJsonExportAndParsing() {
        val categories = listOf(
            BackupCategory(1L, "Shopping", "shopping_bag", "#EC4899", "EXPENSE", true)
        )
        val transactions = listOf(
            BackupTransaction(501L, 159900L, "EXPENSE", 1L, "CASH", "Shoes", 1787400000000L)
        )

        val json = JsonBackupParser.exportTransactionsToJson(transactions, categories)
        assertTrue(json.contains("\"count\": 1"))
        assertTrue(json.contains("\"Shoes\""))

        val parsed = JsonBackupParser.parseTransactionsJson(json)
        assertEquals(1, parsed.size)
        assertEquals(501L, parsed[0].id)
        assertEquals(159900L, parsed[0].amountSubunits)
        assertEquals("EXPENSE", parsed[0].type)
        assertEquals("CASH", parsed[0].paymentMethod)
    }
}
