package com.vinaynalavade.expensetracker

import com.vinaynalavade.expensetracker.core.backup.BackupCategory
import com.vinaynalavade.expensetracker.core.backup.BackupData
import com.vinaynalavade.expensetracker.core.backup.BackupPreferences
import com.vinaynalavade.expensetracker.core.backup.BackupRecurringTransaction
import com.vinaynalavade.expensetracker.core.backup.BackupTransaction
import com.vinaynalavade.expensetracker.core.backup.BackupValidationResult
import com.vinaynalavade.expensetracker.core.backup.ImportValidationResult
import com.vinaynalavade.expensetracker.core.model.Currency
import com.vinaynalavade.expensetracker.core.result.AppResult
import com.vinaynalavade.expensetracker.domain.model.Category
import com.vinaynalavade.expensetracker.domain.model.PaymentMethod
import com.vinaynalavade.expensetracker.domain.model.RecurrenceFrequency
import com.vinaynalavade.expensetracker.domain.model.RecurringTransaction
import com.vinaynalavade.expensetracker.domain.model.ThemeMode
import com.vinaynalavade.expensetracker.domain.model.Transaction
import com.vinaynalavade.expensetracker.domain.model.TransactionType
import com.vinaynalavade.expensetracker.domain.model.UserPreferences
import com.vinaynalavade.expensetracker.domain.repository.BackupRepository
import com.vinaynalavade.expensetracker.domain.usecase.RestoreBackupUseCase
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class BackupRestoreTest {

    @Test
    fun testFullBackupRestoreReplacesExistingDataSuccessfully() = runBlocking {
        val restoredBackup = BackupData(
            backupVersion = 1,
            appVersion = "1.0.1",
            createdAt = 1787400000000L,
            categories = listOf(
                BackupCategory(100L, "Custom Grocery", "shopping_cart", "#10B981", "EXPENSE", false),
                BackupCategory(101L, "Freelance Income", "work", "#3B82F6", "INCOME", true)
            ),
            transactions = listOf(
                BackupTransaction(500L, 75000L, "EXPENSE", 100L, "UPI", "Weekly fruits", 1787410000000L),
                BackupTransaction(501L, 2000000L, "INCOME", 101L, "BANK_ACCOUNT", "Client payment", 1787420000000L)
            ),
            recurringTransactions = listOf(
                BackupRecurringTransaction(
                    id = 10L,
                    title = "Gym Sub",
                    amountSubunits = 150000L,
                    type = "EXPENSE",
                    categoryId = 100L,
                    paymentMethod = "UPI",
                    note = null,
                    frequency = "MONTHLY",
                    dayOfMonth = 5,
                    dayOfWeek = 1,
                    startDate = 1787000000000L,
                    endDate = null,
                    isEnabled = true,
                    isAutoGenerated = true,
                    reminderDaysBefore = 1,
                    lastGeneratedDate = null,
                    createdAt = 1787000000000L,
                    updatedAt = 1787000000000L
                )
            ),
            preferences = BackupPreferences(
                openingBalanceSubunits = 5000000L,
                currencyCode = "INR",
                themeMode = "DARK",
                dailyReminderEnabled = true,
                dailyReminderHour = 22,
                dailyReminderMinute = 15,
                emiRemindersEnabled = true
            )
        )

        val fakeBackupRepo = FakeFullBackupRepository()
        val restoreUseCase = RestoreBackupUseCase(fakeBackupRepo)

        val result = restoreUseCase(restoredBackup)

        assertTrue(result is AppResult.Success)
        assertEquals(2, fakeBackupRepo.storedCategories.size)
        assertEquals(2, fakeBackupRepo.storedTransactions.size)
        assertEquals(1, fakeBackupRepo.storedRecurring.size)
        assertEquals(5000000L, fakeBackupRepo.storedPreferences?.openingBalanceSubunits)
        assertEquals("DARK", fakeBackupRepo.storedPreferences?.themeMode)
        assertEquals(22, fakeBackupRepo.storedPreferences?.dailyReminderHour)
        assertEquals(15, fakeBackupRepo.storedPreferences?.dailyReminderMinute)
    }

    private class FakeFullBackupRepository : BackupRepository {
        val storedCategories = mutableListOf<BackupCategory>()
        val storedTransactions = mutableListOf<BackupTransaction>()
        val storedRecurring = mutableListOf<BackupRecurringTransaction>()
        var storedPreferences: BackupPreferences? = null

        override fun getLastBackupTimestamp(): Flow<Long?> = flowOf(System.currentTimeMillis())
        override suspend fun createFullBackup(): AppResult<BackupData> = AppResult.Error(com.vinaynalavade.expensetracker.core.result.AppError.DatabaseError("N/A"))
        override suspend fun validateBackupJson(jsonString: String): BackupValidationResult = BackupValidationResult.Invalid("N/A")

        override suspend fun restoreFullBackup(backupData: BackupData): AppResult<Unit> {
            storedCategories.clear()
            storedCategories.addAll(backupData.categories)

            storedTransactions.clear()
            storedTransactions.addAll(backupData.transactions)

            storedRecurring.clear()
            storedRecurring.addAll(backupData.recurringTransactions)

            storedPreferences = backupData.preferences
            return AppResult.Success(Unit)
        }

        override suspend fun getFilteredTransactions(startDate: Long?, endDate: Long?, type: TransactionType?, categoryId: Long?): AppResult<List<Transaction>> = AppResult.Success(emptyList())
        override suspend fun validateAndPrepareImportCsv(csvContent: String, defaultCurrency: Currency): ImportValidationResult = ImportValidationResult(0, emptyList(), emptyList())
        override suspend fun validateAndPrepareImportJson(jsonContent: String): ImportValidationResult = ImportValidationResult(0, emptyList(), emptyList())
        override suspend fun importTransactions(transactions: List<Transaction>): AppResult<Int> = AppResult.Success(transactions.size)
    }
}
