package com.vinaynalavade.expensetracker

import com.vinaynalavade.expensetracker.core.model.Amount
import com.vinaynalavade.expensetracker.core.result.AppError
import com.vinaynalavade.expensetracker.core.result.AppResult
import com.vinaynalavade.expensetracker.core.utils.DateTimeUtils
import com.vinaynalavade.expensetracker.domain.model.Category
import com.vinaynalavade.expensetracker.domain.model.PaymentMethod
import com.vinaynalavade.expensetracker.domain.model.RecurrenceFrequency
import com.vinaynalavade.expensetracker.domain.model.RecurringTransaction
import com.vinaynalavade.expensetracker.domain.model.TransactionType
import com.vinaynalavade.expensetracker.domain.repository.RecurringTransactionRepository
import com.vinaynalavade.expensetracker.domain.usecase.SaveRecurringTransactionUseCase
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import java.time.LocalDate
import java.time.YearMonth

class RecurringEmiDayOfMonthTest {

    private val sampleCategory = Category(
        id = 1L,
        name = "Rent / EMI",
        iconName = "home",
        colorHex = "#FF5722",
        type = TransactionType.EXPENSE
    )

    private lateinit var fakeRepo: FakeRecurringRepository
    private lateinit var saveUseCase: SaveRecurringTransactionUseCase

    @Before
    fun setUp() {
        fakeRepo = FakeRecurringRepository()
        saveUseCase = SaveRecurringTransactionUseCase(fakeRepo)
    }

    private fun createEmi(day: Int, id: Long = 0L): RecurringTransaction {
        return RecurringTransaction(
            id = id,
            title = "Car Loan EMI",
            amount = Amount(2500000L), // ₹25,000
            type = TransactionType.EXPENSE,
            category = sampleCategory,
            paymentMethod = PaymentMethod.BANK_ACCOUNT,
            frequency = RecurrenceFrequency.MONTHLY,
            dayOfMonth = day,
            isEnabled = true,
            isAutoGenerated = true
        )
    }

    // ─── 1. Input & Range Validation Tests ───

    @Test
    fun testValidDaysAreAccepted() = runBlocking {
        val validDays = listOf(1, 15, 28, 29, 30, 31)
        for (day in validDays) {
            val emi = createEmi(day)
            val result = saveUseCase(emi)
            assertTrue("Day $day should be accepted", result is AppResult.Success)
        }
    }

    @Test
    fun testDayZeroIsRejected() = runBlocking {
        val emi = createEmi(0)
        val result = saveUseCase(emi)
        assertTrue(result is AppResult.Error)
        val error = (result as AppResult.Error).error
        assertTrue(error is AppError.ValidationError)
        assertEquals("dayOfMonth", (error as AppError.ValidationError).field)
    }

    @Test
    fun testDay32IsRejected() = runBlocking {
        val emi = createEmi(32)
        val result = saveUseCase(emi)
        assertTrue(result is AppResult.Error)
        val error = (result as AppResult.Error).error
        assertTrue(error is AppError.ValidationError)
        assertEquals("dayOfMonth", (error as AppError.ValidationError).field)
    }

    @Test
    fun testNegativeDayIsRejected() = runBlocking {
        val emi = createEmi(-5)
        val result = saveUseCase(emi)
        assertTrue(result is AppResult.Error)
        val error = (result as AppResult.Error).error
        assertTrue(error is AppError.ValidationError)
        assertEquals("dayOfMonth", (error as AppError.ValidationError).field)
    }

    @Test
    fun testEmptyOrInvalidAmountRejected() = runBlocking {
        val emi = createEmi(15).copy(amount = Amount(0L))
        val result = saveUseCase(emi)
        assertTrue(result is AppResult.Error)
    }

    @Test
    fun testBlankTitleRejected() = runBlocking {
        val emi = createEmi(15).copy(title = "   ")
        val result = saveUseCase(emi)
        assertTrue(result is AppResult.Error)
    }

    // ─── 2. Calendar Scheduling & Clamping Tests ───

    @Test
    fun testDay31SchedulesJanuary31() {
        val jan2026 = YearMonth.of(2026, 1)
        val scheduledDay = DateTimeUtils.getScheduledDayOfMonth(31, jan2026)
        val scheduledDate = DateTimeUtils.getScheduledDate(31, jan2026)

        assertEquals(31, scheduledDay)
        assertEquals(LocalDate.of(2026, 1, 31), scheduledDate)
    }

    @Test
    fun testDay31SchedulesFebruary28InNormalYear() {
        val feb2026 = YearMonth.of(2026, 2)
        val scheduledDay = DateTimeUtils.getScheduledDayOfMonth(31, feb2026)
        val scheduledDate = DateTimeUtils.getScheduledDate(31, feb2026)

        assertEquals(28, scheduledDay)
        assertEquals(LocalDate.of(2026, 2, 28), scheduledDate)
    }

    @Test
    fun testDay31SchedulesFebruary29InLeapYear() {
        val feb2024 = YearMonth.of(2024, 2)
        val scheduledDay = DateTimeUtils.getScheduledDayOfMonth(31, feb2024)
        val scheduledDate = DateTimeUtils.getScheduledDate(31, feb2024)

        assertEquals(29, scheduledDay)
        assertEquals(LocalDate.of(2024, 2, 29), scheduledDate)
    }

    @Test
    fun testDay31SchedulesApril30() {
        val apr2026 = YearMonth.of(2026, 4)
        val scheduledDay = DateTimeUtils.getScheduledDayOfMonth(31, apr2026)
        val scheduledDate = DateTimeUtils.getScheduledDate(31, apr2026)

        assertEquals(30, scheduledDay)
        assertEquals(LocalDate.of(2026, 4, 30), scheduledDate)
    }

    @Test
    fun testDay29SchedulesFebruary28InNonLeapYear() {
        val feb2026 = YearMonth.of(2026, 2)
        val scheduledDay = DateTimeUtils.getScheduledDayOfMonth(29, feb2026)
        val scheduledDate = DateTimeUtils.getScheduledDate(29, feb2026)

        assertEquals(28, scheduledDay)
        assertEquals(LocalDate.of(2026, 2, 28), scheduledDate)
    }

    @Test
    fun testDay29SchedulesFebruary29InLeapYear() {
        val feb2024 = YearMonth.of(2024, 2)
        val scheduledDay = DateTimeUtils.getScheduledDayOfMonth(29, feb2024)
        val scheduledDate = DateTimeUtils.getScheduledDate(29, feb2024)

        assertEquals(29, scheduledDay)
        assertEquals(LocalDate.of(2024, 2, 29), scheduledDate)
    }

    @Test
    fun testDay30SchedulesFebruaryCorrectly() {
        val feb2026 = YearMonth.of(2026, 2)
        val feb2024 = YearMonth.of(2024, 2)

        assertEquals(28, DateTimeUtils.getScheduledDayOfMonth(30, feb2026))
        assertEquals(29, DateTimeUtils.getScheduledDayOfMonth(30, feb2024))
    }

    @Test
    fun testMonthTransitionsAcrossEntireYearForDay31() {
        // Month lengths for 2026 (normal year)
        val expectedDays = listOf(
            Pair(YearMonth.of(2026, 1), 31),
            Pair(YearMonth.of(2026, 2), 28),
            Pair(YearMonth.of(2026, 3), 31),
            Pair(YearMonth.of(2026, 4), 30),
            Pair(YearMonth.of(2026, 5), 31),
            Pair(YearMonth.of(2026, 6), 30),
            Pair(YearMonth.of(2026, 7), 31),
            Pair(YearMonth.of(2026, 8), 31),
            Pair(YearMonth.of(2026, 9), 30),
            Pair(YearMonth.of(2026, 10), 31),
            Pair(YearMonth.of(2026, 11), 30),
            Pair(YearMonth.of(2026, 12), 31)
        )

        for ((ym, expectedDay) in expectedDays) {
            val actualDay = DateTimeUtils.getScheduledDayOfMonth(31, ym)
            assertEquals("Month ${ym.month} should have scheduled day $expectedDay", expectedDay, actualDay)
        }
    }

    @Test
    fun testYearTransitionMaintainsCorrectDay() {
        val dec2025 = YearMonth.of(2025, 12)
        val jan2026 = YearMonth.of(2026, 1)

        assertEquals(31, DateTimeUtils.getScheduledDayOfMonth(31, dec2025))
        assertEquals(31, DateTimeUtils.getScheduledDayOfMonth(31, jan2026))
    }

    // ─── 3. Editing & Persistence Tests ───

    @Test
    fun testEditingExistingEmiUpdatesDayOfMonth() = runBlocking {
        val initialEmi = createEmi(5)
        val insertResult = saveUseCase(initialEmi)
        assertTrue(insertResult is AppResult.Success)
        val id = (insertResult as AppResult.Success).data

        // Edit from day 5 to day 15
        val updatedEmi = fakeRepo.items[id]!!.copy(dayOfMonth = 15)
        val updateResult = saveUseCase(updatedEmi)
        assertTrue(updateResult is AppResult.Success)

        val persisted = fakeRepo.items[id]
        assertEquals(15, persisted?.dayOfMonth)
    }

    @Test
    fun testEditingToDay31PersistsCleanly() = runBlocking {
        val initialEmi = createEmi(28)
        val insertResult = saveUseCase(initialEmi)
        val id = (insertResult as AppResult.Success).data

        // Change from 28 to 31
        val updatedEmi = fakeRepo.items[id]!!.copy(dayOfMonth = 31)
        saveUseCase(updatedEmi)

        val persisted = fakeRepo.items[id]
        assertEquals(31, persisted?.dayOfMonth)
    }

    @Test
    fun testConfiguredDayRemains31AfterClampedOccurrence() = runBlocking {
        // When configured for 31, the stored model retains 31 even if scheduled for Feb 28
        val emi = createEmi(31)
        saveUseCase(emi)

        val feb2026 = YearMonth.of(2026, 2)
        val occurrenceDate = DateTimeUtils.getScheduledDate(emi.dayOfMonth, feb2026)

        assertEquals(LocalDate.of(2026, 2, 28), occurrenceDate)
        assertEquals(31, emi.dayOfMonth) // Model configuration never mutates to 28
    }

    // ─── Fake Repository ───

    private class FakeRecurringRepository : RecurringTransactionRepository {
        val items = mutableMapOf<Long, RecurringTransaction>()
        private var nextId = 1L

        override fun getRecurringTransactions(): Flow<List<RecurringTransaction>> =
            flowOf(items.values.toList())

        override fun getRecurringTransactionById(id: Long): Flow<RecurringTransaction?> =
            flowOf(items[id])

        override suspend fun insertRecurringTransaction(recurringTransaction: RecurringTransaction): AppResult<Long> {
            val id = nextId++
            items[id] = recurringTransaction.copy(id = id)
            return AppResult.Success(id)
        }

        override suspend fun updateRecurringTransaction(recurringTransaction: RecurringTransaction): AppResult<Unit> {
            items[recurringTransaction.id] = recurringTransaction
            return AppResult.Success(Unit)
        }

        override suspend fun deleteRecurringTransaction(id: Long): AppResult<Unit> {
            items.remove(id)
            return AppResult.Success(Unit)
        }

        override suspend fun processDueOccurrences(): AppResult<Int> {
            return AppResult.Success(0)
        }
    }
}
