package com.vinaynalavade.expensetracker.domain.model

import com.vinaynalavade.expensetracker.core.model.Amount

enum class RecurrenceFrequency(val displayName: String) {
    DAILY("Daily"),
    WEEKLY("Weekly"),
    MONTHLY("Monthly"),
    YEARLY("Yearly");

    companion object {
        fun fromStringOrNull(value: String): RecurrenceFrequency? {
            return entries.firstOrNull { it.name.equals(value.trim(), ignoreCase = true) }
        }

        fun fromString(value: String): RecurrenceFrequency {
            return fromStringOrNull(value) ?: MONTHLY
        }
    }
}

data class RecurringTransaction(
    val id: Long = 0L,
    val title: String,
    val amount: Amount,
    val type: TransactionType,
    val category: Category,
    val note: String? = null,
    val frequency: RecurrenceFrequency = RecurrenceFrequency.MONTHLY,
    val dayOfMonth: Int = 1, // 1 - 31 for monthly / yearly
    val dayOfWeek: Int = 1, // 1 (Mon) - 7 (Sun) for weekly
    val startDate: Long = System.currentTimeMillis(),
    val endDate: Long? = null,
    val isEnabled: Boolean = true,
    val isAutoGenerated: Boolean = true,
    val reminderDaysBefore: Int? = null, // e.g. 1, 2, 3, 7 days before due date
    val lastGeneratedDate: Long? = null,
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis()
)
